kubernetes_version: 1.28
pod_network_cidr: 192.168.0.0/16
environment: dev

ansible_user: ubuntu
ansible_ssh_private_key_file: "/home/runner/.ssh/deploy_key.pem"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

master_node: 1
worker_node: 1

k3s_version: "v1.28.8+k3s1"
cluster_context: "k3s-dev"
kubeconfig: "~/.kube/config"
extra_server_args: ""
extra_agent_args: ""
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] }}"