sonar.projectKey=kubezen-stack_cloud-resource-cost
sonar.organization=lavash2310

sonar.sources=src
sonar.tests=src/tests
sonar.test.inclusions=src/tests/**

sonar.python.version=3.11
sonar.python.xunit.reportPath=src/*-results.xml

sonar.sourceEncoding=UTF-8