- name: Check if Helm is already installed
  ansible.builtin.command: which helm
  register: helm_exists
  ignore_errors: true
  changed_when: false
  tags: install

- name: Download Helm installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'
  when: helm_exists.rc != 0
  tags: install

- name: Run Helm installation script
  ansible.builtin.shell: /tmp/get_helm.sh
  when: helm_exists.rc != 0
  tags: install

- name: Delete installation script
  ansible.builtin.file:
    path: /tmp/get_helm.sh
    state: absent
  tags: cleanup

- name: Get ECR authorization token for Secret
  amazon.aws.ecr_auth:
    region: "{{ aws_region | default('us-east-1') }}"
  register: ecr_auth
  tags: ecr_secret

- name: Create cost-optimizer namespace
  kubernetes.core.k8s:
    name: cost-optimizer
    api_version: v1
    kind: Namespace
    state: present
  tags: ecr_secret

- name: Create imagePullSecret in Kubernetes
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ecr-secret
        namespace: cost-optimizer
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ { 'auths': { (ecr_auth.url | ansible.builtin.regex_replace('^https://', '')): { 'auth': ( 'AWS:' + ecr_auth.password ) | ansible.builtin.b64encode } } } | ansible.builtin.to_json | ansible.builtin.b64encode }}"
  tags: ecr_secret

- name: Add Helm repositories
  become: no
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  loop:
    - { name: "bitnami", url: "https://charts.bitnami.com/bitnami" }
    - { name: "jetstack", url: "https://charts.jetstack.io" }
    - { name: "ingress-nginx", url: "https://kubernetes.github.io/ingress-nginx" }
  tags: repos

- name: Update Helm repositories
  become: no
  ansible.builtin.command: helm repo update
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  changed_when: false
  tags: repos

- name: Verify Helm can communicate with Kubernetes
  become: no
  ansible.builtin.command: helm list -A
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  register: helm_list
  changed_when: false
  tags: verify

- name: Deploy Cost Optimizer Helm Chart
  become: no
  kubernetes.core.helm:
    name: cost-optimizer
    chart_ref: "./helm/cost-optimizer"
    release_namespace: cost-optimizer
    values_files:
      - values.yaml
      - "values-{{ target_env }}.yaml"
    values:
      image:
        repository: "{{ ecr_auth.url | ansible.builtin.regex_replace('^https://', '') }}/cost-optimizer-{{ target_env }}"
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  tags: deploy

- name: Display Helm test connection
  ansible.builtin.debug:
    msg: "Helm successfully configured and connected to Kubernetes"
  when: helm_list.rc == 0
  tags: verify