apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cost-optimizer.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "cost-optimizer.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.app.environment | quote }}
  DEBUG: {{ .Values.app.debug | quote }}
  PROJECT_NAME: {{ .Values.app.name | quote }}
  VERSION: {{ .Values.app.version | quote }}
  API_V1_STR: "/api/v1"

  ALGORITHM: {{ .Values.app.algorithm | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.app.accessTokenExpireMinutes | quote }}

  POSTGRES_HOST: {{ .Values.database.host | quote }}
  POSTGRES_PORT: {{ .Values.database.port | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}

  {{- if .Values.app.corsOrigins }}
  CORS_ORIGINS: {{ .Values.app.corsOrigins | join "," | quote }}
  {{- end }}