apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cost-optimizer.fullname" . }}-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ include "cost-optimizer.name" | nindent 4 }}
type: Opaque
stringData:
  secret_key: {{ .Values.database.secretKey | quote }}

  database-password: {{ .Values.database.password | quote }}
  postgres-password: {{ .Values.database.password | quote }}

  database-url: "postgresql+asyncpg://{{ .Values.database.username }}:{{ .Values.database.password | default "qwerty123" }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name}}"