apiVersion: v1
kind: Service
metadata:
  name: { { include "cost-optimizer.fullname" . } }
  namespace: { { .Release.Namespace } }
  labels: { { - include "cost-optimizer.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
      protocol: TCP
      name: http
  selector: { { - include "cost-optimizer.selectorLabels" . | nindent 4 } }
