victoria-metrics-single:
  enabled: true
  server:
    retentionPeriod: 3d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    persistentVolume:
      enabled: false

victoria-metrics-agent:
  enabled: true
  config:
    externalLabels:
      env: "dev"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  remoteWrite:
    - url: "http://monitoring-victoria-metrics-single-server:8428/api/v1/write"

loki:
  enabled: true
  deploymentMode: SingleBinary
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: "filesystem"
    storage_config:
      filesystem:
        directory: /tmp/loki/chunks
    rulerConfig:
      storage:
        type: local
        local:
          directory: /tmp/loki/rules
    schemaConfig:
      configs:
        - from: "2025-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
  singleBinary:
    replicas: 1
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi
  chunksCache:
    enabled: false
  resultsCache:
    enabled: false

promtail:
  enabled: true
  config:
    clients:
      - url: "http://monitoring-loki:3100/loki/api/v1/push"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

grafana:
  enabled: true
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
  additionalDataSources:
    - name: "VictoriaMetrics"
      type: "prometheus"
      url: "http://monitoring-victoria-metrics-single-server:8428"
      isDefault: true
    - name: "Loki"
      type: "loki"
      url: "http://monitoring-loki:3100"

alertmanager:
  enabled: false

prometheus-node-exporter:
  enabled: true
  prometheus:
    monitor:
      enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule