- name: "Common setup for all nodes"
  import_playbook: common.yml

- name: "Set up Kubernetes master"
  import_playbook: master_k8s.yml

- name: "Set up Calico CNI"
  import_playbook: calico.yml

- name: "Set up Kubernetes worker"
  import_playbook: worker_k8s.yml

- name: "Install Helm"
  import_playbook: helm_group.yml

- name: "Install GitHub Actions self-hosted runner"
  import_playbook: github_runner.yml
