- name: "Map AWS groups to k3s groups"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add master to server group
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: server
      loop: "{{ groups['master'] | default([]) }}"

    - name: Add worker to agent group
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: agent
      loop: "{{ groups['worker'] | default([]) }}"

- name: "Common setup for k3s"
  import_playbook: common_k3s.yml

- name: "Deploy K3s cluster"
  import_playbook: ../k3s-ansible/playbooks/site.yml

- name: "Install Helm"
  import_playbook: helm_group.yml

- name: "Install GitHub Actions runner"
  import_playbook: github_runner.yml