- name: restarted containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: restarted kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted

- name: reload sysctl
  ansible.builtin.shell: sysctl --system