"""initial migration

Revision ID: 2f73cd22b315
Revises: 
Create Date: 2026-03-30 20:12:32.940826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f73cd22b315'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('aws_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('aws_account_name', sa.String(), nullable=False),
    sa.Column('aws_account_id', sa.String(), nullable=False),
    sa.Column('role_arn', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_arn')
    )
    op.create_index(op.f('ix_aws_accounts_id'), 'aws_accounts', ['id'], unique=False)
    op.create_table('cost_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aws_account_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usage_quantity', sa.Numeric(), nullable=True),
    sa.Column('usage_unit', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aws_account_id'], ['aws_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_records_date', 'cost_services', ['recorded_at'], unique=False)
    op.create_index('ix_cost_services_aws_account_date', 'cost_services', ['aws_account_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_cost_services_id'), 'cost_services', ['id'], unique=False)
    op.create_index('ix_cost_services_service_name', 'cost_services', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cost_services_service_name', table_name='cost_services')
    op.drop_index(op.f('ix_cost_services_id'), table_name='cost_services')
    op.drop_index('ix_cost_services_aws_account_date', table_name='cost_services')
    op.drop_index('ix_cost_records_date', table_name='cost_services')
    op.drop_table('cost_services')
    op.drop_index(op.f('ix_aws_accounts_id'), table_name='aws_accounts')
    op.drop_table('aws_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
