"""add_validation_fields_and_unique_constraint

Revision ID: 4f51c5ead3e5
Revises: 2cb2e21a092e
Create Date: 2026-05-03 00:21:13.102722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f51c5ead3e5'
down_revision: Union[str, Sequence[str], None] = '2cb2e21a092e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aws_accounts', sa.Column('last_validated_at', sa.DateTime(), nullable=True))
    op.add_column('aws_accounts', sa.Column('last_validation_error', sa.String(), nullable=True))
    op.create_unique_constraint('uq_user_aws_account', 'aws_accounts', ['user_id', 'aws_account_id'])
    op.drop_index('ix_cost_services_aws_account_date', table_name='cost_services')
    op.create_index('ix_cost_services_aws_account_date', 'cost_services', ['aws_account_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cost_services_aws_account_date', table_name='cost_services')
    op.create_index('ix_cost_services_aws_account_account_date', 'cost_services', ['aws_account_id', 'recorded_at'], unique=False)
    op.drop_constraint('uq_user_aws_account', 'aws_accounts', type_='unique')
    op.drop_column('aws_accounts', 'last_validation_error')
    op.drop_column('aws_accounts', 'last_validated_at')
    # ### end Alembic commands ###