argo-cd:
  server:
    service:
      type: NodePort
      nodePort: 30808
  configs:
    params:
      server.insecure: true

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi