argo-cd:
  server:
    service:
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hostname: "HOST_PLACEHOLDER"
      tls: true
      extraTls:
        - secretName: argocd-stage-tls
          hosts:
            - "HOST_PLACEHOLDER"

  configs:
    params:
      server.insecure: true

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
